/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import config.AI;
import config.Game;
import config.HumanPlayer;
import config.OPiece;
import config.Player;
import config.ProbableAI;
import config.XPiece;
import java.awt.Color;
import src.Board;

/**
 *
 * @author mwwie
 */
public class Options extends javax.swing.JPanel {

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        playModeButtons = new javax.swing.ButtonGroup();
        difficultyButtons = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        playerButton = new javax.swing.JRadioButton();
        computerButton = new javax.swing.JRadioButton();
        playerLabel = new javax.swing.JLabel();
        computerLabel = new javax.swing.JLabel();
        playerNamesPanel = new javax.swing.JPanel();
        player1Label = new javax.swing.JLabel();
        player1TextField = new javax.swing.JTextField();
        player2TextField = new javax.swing.JTextField();
        player2Label = new javax.swing.JLabel();
        difficultyButtonsPanel = new javax.swing.JPanel();
        easyDifficultyButton = new javax.swing.JRadioButton();
        mediumDifficultyButton = new javax.swing.JRadioButton();
        hardDifficultyButton = new javax.swing.JRadioButton();
        startButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        titleLabel.setText("Options");

        playModeButtons.add(playerButton);
        playerButton.setSelected(true);
        playerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerButton.setNextFocusableComponent(computerButton);

        playModeButtons.add(computerButton);
        computerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerButton.setNextFocusableComponent(player1TextField);

        playerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerLabel.setText("Player");
        playerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        computerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerLabel.setText("Computer");
        computerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        player1Label.setText("Player 1:");

        player1TextField.setNextFocusableComponent(player2TextField);

        player2TextField.setNextFocusableComponent(easyDifficultyButton);

        player2Label.setText("Player 2:");

        javax.swing.GroupLayout playerNamesPanelLayout = new javax.swing.GroupLayout(playerNamesPanel);
        playerNamesPanel.setLayout(playerNamesPanelLayout);
        playerNamesPanelLayout.setHorizontalGroup(
            playerNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerNamesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerNamesPanelLayout.createSequentialGroup()
                        .addComponent(player1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addGroup(playerNamesPanelLayout.createSequentialGroup()
                        .addComponent(player2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2TextField)))
                .addContainerGap())
        );
        playerNamesPanelLayout.setVerticalGroup(
            playerNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerNamesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label)
                    .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2Label)
                    .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        difficultyButtons.add(easyDifficultyButton);
        easyDifficultyButton.setText("Easy");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, computerButton, org.jdesktop.beansbinding.ELProperty.create("${selected}"), easyDifficultyButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        difficultyButtons.add(mediumDifficultyButton);
        mediumDifficultyButton.setSelected(true);
        mediumDifficultyButton.setText("Medium");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, computerButton, org.jdesktop.beansbinding.ELProperty.create("${selected}"), mediumDifficultyButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        difficultyButtons.add(hardDifficultyButton);
        hardDifficultyButton.setText("Hard");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, computerButton, org.jdesktop.beansbinding.ELProperty.create("${selected}"), hardDifficultyButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout difficultyButtonsPanelLayout = new javax.swing.GroupLayout(difficultyButtonsPanel);
        difficultyButtonsPanel.setLayout(difficultyButtonsPanelLayout);
        difficultyButtonsPanelLayout.setHorizontalGroup(
            difficultyButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(difficultyButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hardDifficultyButton)
                    .addComponent(mediumDifficultyButton)
                    .addComponent(easyDifficultyButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        difficultyButtonsPanelLayout.setVerticalGroup(
            difficultyButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(easyDifficultyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mediumDifficultyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hardDifficultyButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(playerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerNamesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(computerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(computerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(difficultyButtonsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerButton)
                    .addComponent(computerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerLabel)
                    .addComponent(computerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerNamesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(difficultyButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        // Start the game!
        String p1Name = player1TextField.getText();
        String p2Name = player2TextField.getText();
        
        Player p1 = new HumanPlayer(p1Name, Game.XPIECE);
        double prob = 0;
        if(easyDifficultyButton.isSelected()) { prob = 0; }
        else if(mediumDifficultyButton.isSelected()) { prob = 0.75; }
        else { prob = 1; }
        Player p2 = playerButton.isSelected() ? 
                new HumanPlayer(p2Name, Game.OPIECE) : 
                new ProbableAI(p2Name, Game.OPIECE, 2, prob);
        
        Game.game = new Game(p1, p2);
        
        getParent().add(new GamePanel());
        getParent().remove(this);
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton computerButton;
    private javax.swing.JLabel computerLabel;
    private javax.swing.ButtonGroup difficultyButtons;
    private javax.swing.JPanel difficultyButtonsPanel;
    private javax.swing.JRadioButton easyDifficultyButton;
    private javax.swing.JRadioButton hardDifficultyButton;
    private javax.swing.JRadioButton mediumDifficultyButton;
    private javax.swing.ButtonGroup playModeButtons;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player1TextField;
    private javax.swing.JLabel player2Label;
    private javax.swing.JTextField player2TextField;
    private javax.swing.JRadioButton playerButton;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JPanel playerNamesPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
